# Generated by Django 5.1.1 on 2024-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='full_text',
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
